### ISSUE TITLE
等待gps

### ISSUE THREAD

**Issue by hushendian** [SailFlorve/RunHDU#1]
替换百度key，签名，包名之后，定位成功，但是显示等待gps，去开阔地带也不行，主要是想用距离这个功能，有没有不开gps获取距离的办法

**Comment by 17883691516** [comment]
作者你好，现在服务其已经没了，运行起来里面很多功能不可用，比如一些联网的功能，之前存在服务器上的数据还可以找到吗

**Comment by SailFlorve** [comment]
不开GPS就无法获取距离。
